services:
  db-0:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: ft-mariadb:1.0
    container_name: ft-inception-db-0
    networks:
      - inception-network
    expose:
      - 3306
    volumes:
      - ft-inception-db-data:/var/lib/mysql:rw
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    restart: always

  wp-0:
    depends_on:
      - db-0
    image: wordpress:6.8-php8.2-fpm-alpine
    container_name: ft-inception-wp-0
    networks:
      - inception-network
    expose:
      - 9000
    volumes:
      - ft-inception-wp-data:/var/www/html:rw
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db-0:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    restart: always

  ws-0:
    depends_on:
      - wp-0
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: ft-nginx:1.0
    container_name: ft-inception-ws-0
    networks:
      - inception-network
    ports:
      - "8080:80"
    volumes:
      - ft-inception-wp-data:/var/www/html:ro
    restart: always

volumes:
  ft-inception-db-data:
  ft-inception-wp-data:

# volumes:
#   mariadb-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /srv/docker-volumes/mariadb_data

networks:
  inception-network:
    driver: bridge

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt