services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    container_name: mariadb
    networks:
      - inception-network
    expose:
      - 3306
    volumes:
      - DB:/var/lib/mysql:rw
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    restart: always
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 40s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1.0
    container_name: wordpress
    networks:
      - inception-network
    expose:
      - 9000
    volumes:
      - Wordpress:/var/www/html:rw
    secrets:
      - credentials
      - db_password
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    restart: always

  nginx:
    depends_on:
      wordpress:
        condition: service_started
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1.0
    container_name: nginx
    networks:
      - inception-network
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - Wordpress:/var/www/html:ro
    restart: always

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/database
  Wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception-network:
    driver: bridge

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
